@startuml

note top of SuperSuper
  Two levels HSM semantics:
  - instantiation: SuperSuper_entry(); Super1_entry(); S11_entry();
  - canonical T1: g() ->   S11_exit(); Super1_exit(); ->   t1(); ->  Super2_entry(); d(); S21_entry();
  - accepted  T1: g() ->   t1(); ->  S11_exit(); Super1_exit(); ->   Super2_entry(); d(); S21_entry();
end note

state SuperSuper {

  state Super1 {
      [*] --> S11
      Super1: entry: trace Super1_entry;
      Super1: exit:  trace Super1_exit;
      
      S11: entry: trace S11_entry;
      S11: exit:  trace S11_exit;
  }
  
  state Super2 {
      [*] --> S21: /trace d(); 
      Super2: entry: trace Super2_entry;
      Super2: exit:  trace Super2_exit;
      
      S21: entry: trace S21_entry;
      S21: exit:  trace S21_exit;
  }
  
  [*] --> Super1
  SuperSuper: entry: trace SuperSuper;
  
  Super1 --> Super2 : T1 [g()]/trace t1; 
  
}

[*] --> SuperSuper

@enduml

