@startuml

note bottom of SuperSuper
 Miro Samek ch2/p88
end note

[*] --> SuperSuper
state SuperSuper {
  SuperSuper: entry: ;
  SuperSuper: exit: ;

  [*] --> Super2 
  state Super2 {
      Super2: entry: ;
      Super2: exit: ;
      
      [*] --> Super21
      state Super21 {
          Super21: entry: ;
          Super21: exit: ;
	  
          [*] --> S211
          S211: entry: ;
          S211: exit: ;
      }
  }
  
  state Super1 {
      [*] --> S11
      Super1: entry: ;
      Super1: exit: ;
      
      S11: entry: ;
      S11: exit: ;
  }
}


Super21 -[#green]-> Super21 : A 

Super21 -[#orchid]-> S211 : B

Super2 -[#green]-> Super1 : C 
Super1 -[#green]-> Super2 : C 

S211 -[#blue]-> Super21 : D 
S11 -[#blue]-> Super1 : D 
Super1 -[#blue]-> SuperSuper : D 

SuperSuper -[#red]-> S11 : E 

Super2 -[#olive]-> S11 : F 
Super1 -[#olive]-> S211 : F 

Super21 -[#sienna]-> S11 : G 
S11 -[#sienna]-> S211 : G 

S211 -[#coral]-> SuperSuper : H 
S11 -[#coral]-> SuperSuper : H 

--

state Test {
[*] --> Test
Test --> [*]
Test: entry: send event:G to state:SuperSuper ;
}

@enduml

