@startuml

state ClosedSystemEnvironment {
[*] --> AliceDial 
AliceDial: config: noInboundEvents;
AliceDial --> BobPickup : NullEvent [currentState:Alice == state:AIdle] /send event:Dial to state:Alice;

BobPickup: config: noInboundEvents;
BobPickup --> AliceHangup : NullEvent [currentState:Bob == state:BInitiated] /send event:Pickup to state:Bob;

AliceHangup: config: noInboundEvents;
AliceHangup --> CallEnded : NullEvent [currentState:Alice == state:AEstablished] /send event:Hangup to state:Alice;

CallEnded: config: noInboundEvents;
CallEnded --> [*]

ClosedSystemEnvironment: ltl: ltlFinalStates {[]<>(currentState:ClosedSystemEnvironment == state:CallEnded && currentState:Alice == state:Aterminated && currentState:Bob == state:Bterminated)};
}


state Alice {
  [*] --> AIdle
  AIdle --> AInitiated : Dial
  
  AInitiated: entry: send event:INVITE to state:Bob;
  AInitiated --> AInitiated : 1xx
  AInitiated --> AEstablished : 2xx

  AEstablished: entry: send event:ACK to state:Bob;
  AEstablished --> Aterminated : Hangup
  
  Aterminated: entry: send event:BYE to state:Bob;
  Aterminated --> [*]

  //AInitiated: timeout: send event:Hangup to state:Alice;
  AInitiated: precondition: (currentState:Alice != state:BIdle);
  AInitiated: postcondition: (currentState:Alice != state:BInitiated);
  AInitiated: invariant: (currentState:Alice != state:Bterminated);
}

//||

state Bob {
  [*] --> BIdle
  BIdle --> BInitiated : INVITE
  
  BInitiated: entry: send event:1xx to state:Alice;
  BInitiated --> BEstablished : Pickup
  
  BEstablished: entry: send event:2xx to state:Alice;
  BEstablished --> BEstablished : ACK
  BEstablished --> Bterminated : BYE
  
  Bterminated --> [*]

  //BInitiated: timeout: send event:Hangup to state:Alice;
  BInitiated: precondition: (currentState:Bob != state:AIdle);
  BInitiated: postcondition: (currentState:Bob != state:AInitiated);
  BInitiated: invariant: (currentState:Bob != state:Aterminated);
  
}

@enduml

