@startuml

state ClosedSystemEnvironment {
[*] --> AliceDial 
AliceDial: config: noInboundEvents;
AliceDial --> BobPickup : NullEvent [currentState:Alice == state:AIdle] /send event:Dial to state:Alice;

BobPickup: config: noInboundEvents;
BobPickup --> AliceHangup : NullEvent [currentState:Bob == state:BInitiated] /send event:Pickup to state:Bob;

AliceHangup: config: noInboundEvents;
AliceHangup --> CallEnded : NullEvent [currentState:Alice == state:AEstablished] /send event:Hangup to state:Alice;

CallEnded: config: noInboundEvents;
CallEnded --> [*]
}


state Alice {
  [*] --> AIdle
  AIdle --> AInitiated : Dial
  
  AInitiated: entry: send event:INVITE to state:Bob;
  AInitiated --> AInitiated : 1xx
  AInitiated --> AEstablished : 2xx

  //AInitiated: timeout: send event:Hangup to state:Alice;
  //AInitiated: precondition: ((x==y) && (z!=1 || z!=2));
  //AInitiated: postcondition: ((x==y) && (z!=1 || z!=2));
  //AInitiated: invariant: ((x==y) && (z!=1 || z!=2));
  
  AEstablished: entry: send event:ACK to state:Bob;
  AEstablished --> Aterminated : Hangup
  
  Aterminated: entry: send event:BYE to state:Bob;
  Aterminated --> [*]
}

//||

state Bob {
  [*] --> BIdle
  BIdle --> BInitiated : INVITE
  
  BInitiated: entry: send event:1xx to state:Alice;
  BInitiated --> BEstablished : Pickup
  
  BEstablished: entry: send event:2xx to state:Alice;
  BEstablished --> BEstablished : ACK
  BEstablished --> Bterminated : BYE
  
  Bterminated --> [*]
}

@enduml

