@startuml

note as N1
  plantuml limitations:
  - state names must be unique
  - no explicit on entry/exit notation
  - cannot draw sending events between 
    states in different regions
end note

state Alice {
  [*] --> AIdle
  AIdle --> AInitiated : Dial [guard] /effect
  
  AInitiated: entry: send INVITE to Bob;
  AInitiated --> AInitiated : 1xx
  AInitiated --> AEstablished : 2xx
  
  AEstablished: entry: send ACK to Bob;
  AEstablished --> Aterminated : Hangup
  
  Aterminated: entry: send BYE to Bob;
  Aterminated --> [*]
}

||

state Bob {
  [*] --> BIdle
  BIdle --> BInitiated : INVITE
  
  BInitiated: entry: send 1xx to Alice;
  BInitiated --> BEstablished : Pickup
  
  BEstablished: entry: send 2xx to Alice;
  BEstablished --> Bterminated : BYE
  
  Bterminated --> [*]
}

@enduml

