

@startuml


#one line comment
// one line comment
/*
 multi line
 comment
 */

hide empty description
state "long state name" as ignored
#state alias4 as "long name"
note left of active : this is a note
note left of active
  line
  line
end note

#Deploy : this  is useless

Deploy -1down-> Operation : Event1 [Guard] / Effect
Deploy --> Operation  

state Operation {

[*] -2down-> Operation_Launch

Operation_Launch -2down-> Operation_Auto_Monitor
--
[*] -3down-> Operation_BizData_Collection

Operation_BizData_Collection -3down-> Operation_BizData_Anylasis
||
[*] -4down-> Operation_Next_Preparation

}

Operation -5down-> [*]

@enduml

